version: "3"

services:
  flaskapp:
    build: .
    container_name: flaskapp
    environment:
      - TZ=$DCK_TZ
      - UID=$DCK_UID
      - GID=$DCK_GID
      - GMG_DATABASE_UIR=$GMG_DATABASE_URI
      - GMG_SECRET=$GMG_SECRET
    secrets:
      - gmg_database_uri
      - gmg_secret
    networks:
      - netpriv
      - netpub
    volumes:
      - ./data/src:/usr/src/app
    labels:
      - traefik.enable=true

      # CORS
      - traefik.http.middlewares.flaskapp-cors-headers.headers.accesscontrolallowmethods=PUT,GET,POST,OPTIONS
      - traefik.http.middlewares.flaskapp-cors-headers.headers.accesscontrolalloworiginlist=https://buzaco.es,https://www.buzaco.es
      - traefik.http.middlewares.flaskapp-cors-headers.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.flaskapp-cors-headers.headers.addvaryheader=true

      # Secure Web UI (Descomentar si se usa HTTPS)
      - traefik.http.routers.flaskapp-https.rule=Host(`buzaco.es`, `www.buzaco.es`)
      - traefik.http.routers.flaskapp-https.entrypoints=websecure
      - traefik.http.routers.flaskapp-https.middlewares=ratelimit@file,secure-headers@file,norobots-headers@file,flaskapp-cors-headers@docker
      - traefik.http.routers.flaskapp-https.tls=true
      - traefik.http.routers.flaskapp-https.tls.certresolver=letsencrypt
      - traefik.http.routers.flaskapp-https.tls.domains[0].main=buzaco.es
      - traefik.http.routers.flaskapp-https.tls.domains[0].sans=*.buzaco.es
      - traefik.http.routers.flaskapp-https.service=flaskapp-https-service
      - traefik.http.services.flaskapp-https-service.loadbalancer.server.port=8080

    restart: unless-stopped
    hostname: "flaskapp"

secrets:
  postgres_admin_password:
    file: $DCK_GMG_SECRETSDIR/gmg_database_uri
  postgres_admin_password:
    file: $DCK_GMG_SECRETSDIR/gmg_secret

networks:
  netpub:
    name: "net-public"
  netpriv:
    name: "net-private"
    internal: true
