version: "3"

services:
  flaskapp:
    build: .
    container_name: flaskapp
    environment:
      - TZ=Europe/Madrid
    networks:
      - netpriv
      - traefik-global
    volumes:
      - ./data/src:/app
    labels:
      - traefik.enable=true

      # CORS
      - traefik.http.middlewares.flaskapp-cors-headers.headers.accesscontrolallowmethods=GET,OPTIONS
      - traefik.http.middlewares.flaskapp-cors-headers.headers.accesscontrolalloworiginlist=https://buzaco.es,https://www.buzaco.es
      - traefik.http.middlewares.flaskapp-cors-headers.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.flaskapp-cors-headers.headers.addvaryheader=true

      # Secure Web UI (Descomentar si se usa HTTPS)
      - traefik.http.routers.flaskapp-https.rule=Host(`buzaco.es`, `www.buzaco.es`)
      - traefik.http.routers.flaskapp-https.entrypoints=websecure
      - traefik.http.routers.flaskapp-https.middlewares=low-ratelimit@file,secure-headers@file,norobots-headers@file,flaskapp-cors-headers@docker
      - traefik.http.routers.flaskapp-https.tls=true
      - traefik.http.routers.flaskapp-https.tls.certresolver=letsencrypt
      - traefik.http.routers.flaskapp-https.tls.domains[0].main=buzaco.es
      - traefik.http.routers.flaskapp-https.tls.domains[0].sans=*.buzaco.es
      - traefik.http.routers.flaskapp-https.service=flaskapp-https-service
      - traefik.http.services.flaskapp-https-service.loadbalancer.server.port=8080

    restart: unless-stopped
    hostname: "flaskapp"

networks:
  traefik-global:
    name: "traefik-global"
  netpriv:
    name: "net-private"
    internal: true
